Part1:

code = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
exon1 = code[0:63]
exon2 = code[90:]
print(exon1 + exon2)

Part2:

from __future__ import division
code = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
exon1 = code[0:63]
exon2 = code[90:]
exonlength = len(exon1 + exon2)
codelength = len(code)
print(100 * exonlength / codelength)

Part3:

code = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
exon1 = code[0:63]
intron = code[63:90]
exon2 = code[90:]
print(exon1 + intron.lower() + exon2)